### ISSUE TITLE
bathymetry

### ISSUE THREAD

**Issue by eclare108213** [CICE-Consortium/CICE#53] opened 2017-12-17 02:23 UTC
Include bathymetric information (vertical grid) as part of standard grid input, for use by fast-ice parameterization and icebergs.

**Comment by phil-blain** [comment] 2018-10-24 20:39
Hi everyone, I'm running some tests of the landfast parameterization with JF on the gx1 grid and we want to check the bathymetry file. Is there a netCDF version of the gx1 grid ? the version I've downloaded from the GitHub wiki is in binary format (CICE_data/grid/gx1/grid_gx1.bin).

**Comment by eclare108213** [comment] 2018-10-24 20:42
Hi Philippe, I don't think we've ever put the gx1 grid data into netcdf.  It exists for gx3.

**Comment by dabail10** [comment] 2018-10-24 20:53
I have netCDF versions that we use in CESM. The problem is that the KMT (land-ocean mask) may be different from your grid. I will send it by email and you can try it out.

**Comment by phil-blain** [comment] 2018-10-30 20:08
Hi everyone,
I just finished running some tests of the new parameterizations (grounding, ellipse ratio, tensile strength) on the gx1 grid with the latest bathymetry files that JF created. The parameterizations work as expected : increasing `k1` and `Ktens` increases the amount of landfast ice, and decreasing `e_ratio` also increases the amount of landfast ice. 
The attached images show the landfast area for the East Siberian, Laptev and Kara seas. The standard run is with basal stress turned off, and default values for `e_ratio` (2.) and `Ktens` (0.). All other runs are with basal stress turned on. When indicated otherwise, parameters are `k1` =8.,  `e_ratio` =2.,  `Ktens` =0.

![east_siberian](https://user-images.githubusercontent.com/44212482/47746932-93877f00-dc5d-11e8-9abf-c7ed1e4fb617.png)
![laptev](https://user-images.githubusercontent.com/44212482/47746926-91252500-dc5d-11e8-96c6-a9248e67fe4b.png)
![kara](https://user-images.githubusercontent.com/44212482/47746920-8bc7da80-dc5d-11e8-8875-227c54a26f31.png)

Note that the initial condition has a lot of ice, particularly in the East Siberian sea, and so the agreement with the data is not perfect.

**Comment by eclare108213** [comment] 2018-10-30 22:01
@phil-blain, thank you for this!  It would be nice to include these results as part of our "sample output" pages for the CICE v6 release.  @duvivier and I have been thinking about how to organize that.  Do you have maps with and without fast ice, or is it not really visible that way?  What is the metric you use to identify fast ice in these timeseries plots?

**Comment by phil-blain** [comment] 2018-10-31 13:55
Yes, I do have boolean maps showing where the ice is landfast for the different runs. I can post some here if you like. As for the metric : from daily model outputs, we compute the mean ice concentration and velocity (in magnitude) over a 14 days period. If the concentration > 0.5 and the velocity < 5E-4, the ice is considered landfast.

**Comment by JFLemieux73** [comment] 2018-10-31 14:03
This is the same metric we used in our papers on landfast ice (e.g. Lemieux et al 2016). Philippe, I suggest you show maps (3) of the landfast ice cover at the end of April for the NIC data, the standard model and the run with e=1.4 (and k1=8).

**Comment by dabail10** [comment] 2018-10-31 14:44
So, are you ready for me to issue the PR on this?

**Comment by JFLemieux73** [comment] 2018-10-31 14:57
Go ahead Dave. Thanks for your help on this. 

I also wanted to test how are the stresses when we change the parameters for the ellipse (not sure this is the right place to post these...maybe also on the sample output page?). Here is a plot of the normalized principal stresses. The yield curve changes are consistent with the modified parameters.

![norm_stresses](https://user-images.githubusercontent.com/31927797/47796898-29361380-dd1d-11e8-9f25-d2d3893a0b93.png)

**Comment by phil-blain** [comment] 2018-10-31 15:24
Here are the maps showing the landfast cells, for the standard run and the one with `k1=8`, `e_ratio=0.2`. The NIC data is interpolated on a higher resolution grid (0.25° ).
![map_std](https://user-images.githubusercontent.com/44212482/47798718-4eb42480-dcff-11e8-82f8-6aa478db860c.png)
![map_eratio](https://user-images.githubusercontent.com/44212482/47798717-4eb42480-dcff-11e8-9ab2-0384814a6403.png)
![map_data](https://user-images.githubusercontent.com/44212482/47798716-4eb42480-dcff-11e8-9ba6-ef1ca21a6629.png)

**Comment by eclare108213** [comment] 2018-10-31 15:35
Very nice, thank you.  (I like the ellipse plots too!)  It's clear that the landfast ice "sticks" to whatever little point of land (or island) is jutting out into the flow.  Have you done resolution studies to see how much that matters?  The ocean bathymetry resolution probably also makes some difference.

**Comment by eclare108213** [comment] 2018-10-31 20:48
Thanks @JFLemieux73 
For the 'sample output' pages we want to show output from actual test runs, so that users can reproduce them to verify that their setup is correct.  We never recommend using gx3 for science.
This all looks great to me!

**Comment by phil-blain** [comment] 2018-11-01 19:09
JF and I did a quick test of the basal stress parameterization with the EAP rheology. This had not been tested before. The results look good. 
![east_siberian](https://user-images.githubusercontent.com/44212482/47873536-e12ff300-dde7-11e8-814a-a28acd0a3913.png)
![kara](https://user-images.githubusercontent.com/44212482/47873537-e12ff300-dde7-11e8-845d-7b75da3fb284.png)
![laptev](https://user-images.githubusercontent.com/44212482/47873538-e12ff300-dde7-11e8-93a3-ed814ec811a0.png)

**Comment by duvivier** [comment] 2018-11-06 20:19
@JFLemieux73 @phil-blain 
I have added these figures to the "Sample output page"
https://github.com/CICE-Consortium/CICE/wiki/CICE-Sample-output#cice-v600---landfast-ice

I'm not sure if we should include both the sets of seasonal figures, but you can let me know if I should remove one. I also added some preliminary captions but I can modify these as you wish too.

**Comment by phil-blain** [comment] 2018-11-06 20:48
Thanks Alice! I've just tried to do some slight modifications to the captions by following the procedure at the bottom of the CICE-Sample-Output page but I think I'm not authorized to do that (`remote: Permission to CICE-Consortium/CICE.wiki.git denied to phil-blain.`). Anyway, the Kara and Laptev captions are inversed in the EAP figures, and for the first yearly figure I'd go with "Area of landfast ice ...... with various parameters" since we vary different parameters than the ellipse ratio.

**Comment by duvivier** [comment] 2018-11-06 21:41
Fixed those captions, thanks Phil!

**Comment by duvivier** [comment] 2018-11-07 20:53
Was this addressed fully by PR #222? If so, should we close the issue?

**Closed** 2018-12-01 02:50 UTC
Labels: infrastructure
